# Generated by Django 5.2.5 on 2025-08-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(help_text="user_name", max_length=100)),
                (
                    "email",
                    models.EmailField(
                        help_text="user_email", max_length=254, unique=True
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, help_text="first_name", max_length=100, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, help_text="last_name", max_length=100, null=True
                    ),
                ),
                ("password", models.CharField(help_text="password", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
